version: 2.1

jobs:
  build:
    docker:
      - image: node:20
    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare --activate

      - run:
          name: Install Dependencies
          command: |
            pnpm install

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

      - run:
          name: ESlint
          command: pnpm eslint

      - run:
          name: Compile
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ];then
              pnpm compile
            fi

      - run:
          name: Deploy to NPM
          command: |
            if [ "${CIRCLE_BRANCH}" = "develop" ];then
              echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
              node ./build/publishDev.js
            fi
