name: Build and deploy jekyll-stage.legumeinfo.org or www.legumeinfo.org

on:
  push:
    branches:
      - 'main'
    tags:
      - '**'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # for legumeinfo/jekyll-theme-legumeinfo submodule (while it's still used)
          submodules: recursive

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: install dependencies and build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: .

      - name: install html-proofer
        run: gem install html-proofer -v 4.2.0
      - name: run html-proofer
        # always exit with status 0 for now, until the list of HTML grievances can be managed
          # --disable-external included for efficiency, eventually remove?
        run: htmlproofer --disable-external --assume-extension --empty-alt-ignore --ignore-files '/uikit/tests/' ./_site || exit 0

      - name: Deploy (stage)
        uses: peaceiris/actions-gh-pages@v3
        # Always deploy for now, despite htmlproofer errors (eventually remove)
        if: github.ref_type == 'branch' && always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: 'jekyll-stage.legumeinfo.org'
          cname: jekyll-stage.legumeinfo.org

      - name: Deploy (prod)
        uses: peaceiris/actions-gh-pages@v3
        # Always deploy for now, despite htmlproofer errors (eventually remove)
        if: github.ref_type == 'tag' && always()
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_site
          external_repository: legumeinfo/legumeinfo.org
          publish_branch: www.legumeinfo.org
          cname: www.legumeinfo.org
